/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GuildsRouteImport } from './routes/guilds'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuildsGuildIdRouteImport } from './routes/guilds.$guildId'
import { Route as GuildsGuildIdRequestsRouteImport } from './routes/guilds.$guildId.requests'
import { Route as GuildsGuildIdRaidsRouteImport } from './routes/guilds.$guildId.raids'
import { Route as GuildsGuildIdManageRouteImport } from './routes/guilds.$guildId.manage'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsRoute = GuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdRoute = GuildsGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => GuildsRoute,
} as any)
const GuildsGuildIdRequestsRoute = GuildsGuildIdRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdRaidsRoute = GuildsGuildIdRaidsRouteImport.update({
  id: '/raids',
  path: '/raids',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)
const GuildsGuildIdManageRoute = GuildsGuildIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => GuildsGuildIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/guilds/$guildId/manage': typeof GuildsGuildIdManageRoute
  '/guilds/$guildId/raids': typeof GuildsGuildIdRaidsRoute
  '/guilds/$guildId/requests': typeof GuildsGuildIdRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/guilds/$guildId/manage': typeof GuildsGuildIdManageRoute
  '/guilds/$guildId/raids': typeof GuildsGuildIdRaidsRoute
  '/guilds/$guildId/requests': typeof GuildsGuildIdRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guilds': typeof GuildsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/guilds/$guildId': typeof GuildsGuildIdRouteWithChildren
  '/guilds/$guildId/manage': typeof GuildsGuildIdManageRoute
  '/guilds/$guildId/raids': typeof GuildsGuildIdRaidsRoute
  '/guilds/$guildId/requests': typeof GuildsGuildIdRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guilds'
    | '/settings'
    | '/guilds/$guildId'
    | '/guilds/$guildId/manage'
    | '/guilds/$guildId/raids'
    | '/guilds/$guildId/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guilds'
    | '/settings'
    | '/guilds/$guildId'
    | '/guilds/$guildId/manage'
    | '/guilds/$guildId/raids'
    | '/guilds/$guildId/requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guilds'
    | '/settings'
    | '/guilds/$guildId'
    | '/guilds/$guildId/manage'
    | '/guilds/$guildId/raids'
    | '/guilds/$guildId/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuildsRoute: typeof GuildsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds': {
      id: '/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof GuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId': {
      id: '/guilds/$guildId'
      path: '/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof GuildsGuildIdRouteImport
      parentRoute: typeof GuildsRoute
    }
    '/guilds/$guildId/requests': {
      id: '/guilds/$guildId/requests'
      path: '/requests'
      fullPath: '/guilds/$guildId/requests'
      preLoaderRoute: typeof GuildsGuildIdRequestsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/raids': {
      id: '/guilds/$guildId/raids'
      path: '/raids'
      fullPath: '/guilds/$guildId/raids'
      preLoaderRoute: typeof GuildsGuildIdRaidsRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
    '/guilds/$guildId/manage': {
      id: '/guilds/$guildId/manage'
      path: '/manage'
      fullPath: '/guilds/$guildId/manage'
      preLoaderRoute: typeof GuildsGuildIdManageRouteImport
      parentRoute: typeof GuildsGuildIdRoute
    }
  }
}

interface GuildsGuildIdRouteChildren {
  GuildsGuildIdManageRoute: typeof GuildsGuildIdManageRoute
  GuildsGuildIdRaidsRoute: typeof GuildsGuildIdRaidsRoute
  GuildsGuildIdRequestsRoute: typeof GuildsGuildIdRequestsRoute
}

const GuildsGuildIdRouteChildren: GuildsGuildIdRouteChildren = {
  GuildsGuildIdManageRoute: GuildsGuildIdManageRoute,
  GuildsGuildIdRaidsRoute: GuildsGuildIdRaidsRoute,
  GuildsGuildIdRequestsRoute: GuildsGuildIdRequestsRoute,
}

const GuildsGuildIdRouteWithChildren = GuildsGuildIdRoute._addFileChildren(
  GuildsGuildIdRouteChildren,
)

interface GuildsRouteChildren {
  GuildsGuildIdRoute: typeof GuildsGuildIdRouteWithChildren
}

const GuildsRouteChildren: GuildsRouteChildren = {
  GuildsGuildIdRoute: GuildsGuildIdRouteWithChildren,
}

const GuildsRouteWithChildren =
  GuildsRoute._addFileChildren(GuildsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuildsRoute: GuildsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
